//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.10 at 10:54:41 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zeus.ctrip.com/model/config", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ctrip.zeus.model.config;
